server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true
    session:
      timeout: 43200m
      cookie:
        max-age: 43200m
        name: SID
        http-only: true # js 조회 안됨
        secure: true # https
eureka:
  instance:
    instance-id: gateway-microservice-instance
    appname: gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-service
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      routes:
        - id: ohlot-service
          uri: lb://ohlot-service
          predicates:
            - Path=/good-words/**
