spring:
  # components:support:swagger
  main:
    allow-bean-definition-overriding: true
  # components:module:auth
  redis:
    host: localhost
    port: 6379
  session:
    store-type: redis
    redis:
      flush-mode: immediate


# components:support:token
support:
  jwt:
    secret-key: secretKey

# components:module:auth-store
filter:
  exclude-list:
    - /auth/**

# :components:client:member
client:
  member:
    url: http://localhost:8788/members