spring:
  # components:support:swagger
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: local
  # components:module:auth-store
  redis:
    host: localhost
    port: 6379
  session:
    store-type: redis
    redis:
      flush-mode: immediate

# components:module:gateway
server:
  servlet:
    session:
      timeout: 43200m
      cookie:
        max-age: 43200m
        name: SID
        http-only: true # js 조회 안됨
        secure: true # https

# components:support:token
support:
  jwt:
    secret-key: secretKey

# components:module:auth-store
filter:
  exclude-list:
    - /auth/**