spring:
  profiles:
    active: local
  redis:
    host: localhost
    port: 6379
  session:
    store-type: redis
    redis:
      flush-mode: immediate
  main:
    allow-bean-definition-overriding: true
support:
  jwt:
    secret-key: secretKey